name: humble

on:
  push:
    branches:
      - humble
  pull_request:
    types: [opened, synchronize, closed]


jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: plotjuggler
          target-ros2-distro: humble
