name: jazzy

on:
  push:
    branches:
      - humble
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: plotjuggler_ros
          target-ros2-distro: jazzy
